version: '3.9'

services:
    website:
        build: bettervanilla
        expose:
            - 3000
        restart: always
        depends_on:
            - reverseproxy
    reverseproxy:
        build: nginx
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - "${HOME}/keys:/etc/ssl/private/"
        restart: always